name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests

      - name: Get PR Diff
        id: pr_diff
        run: |
          echo "Fetching PR diff..."
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.diff" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
               > pr_diff.txt

      - name: Run AI Code Review
        run: python .github/scripts/review_code.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

